language: c

after_failure:
    - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"**zpl** started the fire! :negative_squared_cross_mark: https://youtu.be/_qxZOB9GxQM?t=209"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN

after_success:
    - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"**zpl** build went fine! :white_check_mark: https://youtu.be/oN5gFLK96Sg?t=85"}' https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_CHANNEL_ID/$DISCORD_WEBHOOK_TOKEN
    - curl -s https://codecov.io/bash

script:
    - mkdir -p build
    - export INCLUDES="-Icode"
    - export LINKER="-pthread -lm -ldl"
    - gcc -g -std=c99 $INCLUDES test/build-test.c $LINKER -o build/test-gcc-c.o
    - clang -coverage -g -std=c99 $INCLUDES test/build-test.c $LINKER -o build/test-clang-c.o
    - g++ -g -std=c++11 $INCLUDES test/build-test.cpp $LINKER -o build/test-gpp-cpp.o
    - clang++ -g -std=c++11 $INCLUDES test/build-test.cpp $LINKER -o build/test-clang-cpp.o
    - gcov test/build-test.c
