name: continuous-integration
on:
  push:
    # paths:
    #   - 'Code/*'
    #   - 'Vendors/*'

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create build folder
        run: mkdir build ; cd build

      - name: Run cmake generator
         run: cmake ../misc

      - name: Run Windows build
         run: cmake --build .

      - name: Run unit tests
         run: cd Debug ; zpl_unit.exe

  build-lin:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run build on Linux
        run: make

  build-mac:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run build on macOS
        run: make
