name: continuous-integration
on:
  push:
    # paths:
    #   - 'Code/*'
    #   - 'Vendors/*'

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run cmake generator
        run: mkdir build ; cd build ; cmake ../misc

      - name: Run Windows build
        run: cd build ; cmake --build .

      - name: Run unit tests
        run: cd build ; dir ; cd Debug ; dir

  build-lin:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run build on Linux
        run: make

  build-mac:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run build on macOS
        run: make
