name: tester
on:
  push:
    branches:
      - master
      - review/*
    paths:
      - 'code/**'
  pull_request:
    branches:
      - master
    paths:
      - 'code/**'

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run cmake generator
        run: mkdir build ; cd build ; cmake ../misc
      - name: Run Windows build
        run: cd build ; cmake --build .
      - name: Run unit tests
        run: cd build ; .\Debug\tester.exe

  build-lin:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          description: "**ZPL** has started the fire trial! (Running tests...)"
          nodetail: true
          nofail: true
          color: "0xFFA500"
          username: "Michael Scott"
          avatar_url: "http://raw.madaraszd.net/office/test.jpg"
      - name: Run build on Linux
        run: make
      - uses: sarisia/actions-status-discord@v1
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          description: "**ZPL** tests have succeeded!"
          nodetail: true
          nofail: true
          color: "0x55df2a"
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          description: "**ZPL** tests have failed!"
          nodetail: true
          nofail: true
          color: "0xdf332a"
          username: "Devastated Michael Scott"
          avatar_url: "http://raw.madaraszd.net/office/fail.jpg"

  build-mac:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run build on macOS
        run: make
